env:
  TERM: xterm-256color
  #TERM: alacritty

window:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: full
font:
  normal:
    family: JetBrains Mono Nerd Font
  size: 10.5

color_schemes:
    solarized_light: &solarized_light
      primary:
        background: '0xfcf0cf'
        foreground: '0x425257'

      # Normal colors
      normal:
        black:   '0x073642'
        red:     '0xdc322f'
        green:   '0x859900'
        yellow:  '0xb58900'
        blue:    '0x268bd2'
        magenta: '0xd33682'
        cyan:    '0x2aa198'
        white:   '0xeee8d5'

      # Bright colors
      bright:
        black:   '0x002b36'
        red:     '0xcb4b16'
        green:   '0x586e75'
        yellow:  '0x657b83'
        blue:    '0x839496'
        magenta: '0x6c71c4'
        cyan:    '0x93a1a1'
        white:   '0xfdf6e3'

    indexed_colors: []

    mytheme: &mytheme
      primary:
        background: '#0b090a'
        foreground: '#dedede'
      normal:
        black:   '#2e3436'
        red:     '#cc0000'
        green:   '#4e9e06'
        yellow:  '#c4a000'
        blue:    '#3465a4'
        magenta: '#75507b'
        cyan:    '#06989a'
        white:   '#d3d7cf'

      # Bright colors
      bright:
        black:   '#555753'
        red:     '#ef2929'
        green:   '#8ae234'
        yellow:  '#ff9712'
        blue:    '#729fcf'
        magenta: '#ad7fa8'
        cyan:    '#1ab2e2'
        white:   '#eeeeec'

    atelierheath: &atelierheath
      primary:
        background: "#f7f3f7"
        foreground: "#695d69"
      cursor:
        text: "#f7f3f7"
        cursor: "#695d69"
      normal:
        black: "#1b181b"
        red: "#ca402b"
        green: "#379a37"
        yellow: "#bb8a35"
        blue: "#516aec"
        magenta: "#7b59c0"
        cyan: "#159393"
        white: "#ab9bab"
      bright:
        black: "#776977"
        red: "#ca402b"
        green: "#379a37"
        yellow: "#bb8a35"
        blue: "#516aec"
        magenta: "#7b59c0"
        cyan: "#159393"
        white: "#f7f3f7"

    light: &light
      primary:
        background: "#ffffff"
        foreground: "#000000"
      cursor:
        text: "#ffffff"
        cursor: "#373b41"
      normal:
        black: "#1d1f21"
        red: "#cc6666"
        green: "#b5bd68"
        yellow: "#f0c674"
        blue: "#81a2be"
        magenta: "#b294bb"
        cyan: "#8abeb7"
        white: "#c5c8c6"
      bright:
        black: "#969896"
        red: "#cc6666"
        green: "#b5bd68"
        yellow: "#f0c674"
        blue: "#81a2be"
        magenta: "#b294bb"
        cyan: "#8abeb7"
        white: "#ffffff"
        # themes : solarized_light, mytheme, atelierheath
colors: *solarized_light

background_opacity: 0.85

cursor:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Underline

  vi_mode_style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true
  blinking: Off  
  blink_interval: 100000

shell:
  program: /bin/bash
mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  url:
    launcher:
      program: firefox-bin
    #  args: []

key_bindings:
    - { key: Return,     mods: Shift|Control,     action: SpawnNewInstance }
    - { key: F11,                                 action: ToggleFullscreen }
