#! /bin/sh
gap=8
PANEL_HEIGHT=27
export gap
export PANEL_HEIGHT

# Configs
#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
#bspc config border_radius 5
#bspc config top_padding $(($PANEL_HEIGHT+$gap))
#bspc config top_padding $PANEL_HEIGHT
#bspc config left_padding $gap
#bspc config right_padding $gap
#bspc config bottom_padding $gap
#bspc config paddingless_monocle true
#bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child
#bspc rule -a '*:*' split_dir=west
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true
bspc config window_gap $gap;
bspc config gapless_monocle true #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle true
bspc config single_monocle false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# Do not follow window on opening
bspc config ignore_ewmh_focus true
##Color settings
#bspc config focused_border_color "#81A1F1"
#bspc config normal_border_color "#4C566A"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"
bspc config border_width 0
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
#Settings for manual splitting
bspc config split_ratio         0.52

#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 1 2 3 4 5 6 #7 8 9
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d I II III IV V VI

###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

# Rules
bspc rule -a Lxappearance state=floating center=true
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a libreoffice-startcenter state=tiled
bspc rule -a libreoffice-* state=tiled
bspc rule -a Thunderbird desktop=^6
bspc rule -a TelegramDesktop desktop=^4
bspc rule -a Signal desktop=^4
bspc rule -a Gimp-2.10 state=floating desktop=^3
bspc rule -a firefox desktop='^1' follow=off
bspc rule -a feh state=floating
#bspc desktop 9 --layout monocle
bspc rule -a Qalculate-gtk state=floating

$HOME/.config/bspwm/autostart.sh
